//
// Created by 林智超 on 2019-06-16.
//

#ifndef UNIXFILESYSTEM_CONST_H
#define UNIXFILESYSTEM_CONST_H


#define MODE_DIR	01000
#define MODE_FILE	00000
#define FILE_DEF_PERMISSION 0664
#define DIR_DEFAULT_PERMISSION	0755
#define FILE_BUFFER 10000
#define BLOCK_SIZE	512
#define INODE_SIZE	128
#define MAX_NAME_SIZE 28
#define INODE_NUM	640
#define BLOCK_NUM	10240
#define BLOCKS_PER_GROUP 64
#define IMAGEFILENAME "data.img"
#define SUPERBLOCK_START_ADDR 0
#define INODEBITMAP_START_ADDR 1*BLOCK_SIZE
#define BLOCKBIITMAP_START_ADDR INODEBITMAP_START_ADDR + 2*BLOCK_SIZE
#define INODE_START_ADDR BLOCKBIITMAP_START_ADDR + 20*BLOCK_SIZE
#define BLOCK_STARTADDR INODE_START_ADDR + INODE_NUM/(BLOCK_SIZE/INODE_SIZE) * BLOCK_SIZE
#define ROOT_DIR_ADDR INODE_START_ADDR
#define HOSTNAME "chaosmyth"


#endif //UNIXFILESYSTEM_CONST_H
